// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers.events;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AuthDetails extends Table {
  public static AuthDetails getRootAsAuthDetails(ByteBuffer _bb) { return getRootAsAuthDetails(_bb, new AuthDetails()); }
  public static AuthDetails getRootAsAuthDetails(ByteBuffer _bb, AuthDetails obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AuthDetails __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String realmId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer realmIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer realmIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String clientId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer clientIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer clientIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String userId() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer userIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String ipAddress() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ipAddressAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer ipAddressInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createAuthDetails(FlatBufferBuilder builder,
      int realmIdOffset,
      int clientIdOffset,
      int userIdOffset,
      int ipAddressOffset) {
    builder.startObject(4);
    AuthDetails.addIpAddress(builder, ipAddressOffset);
    AuthDetails.addUserId(builder, userIdOffset);
    AuthDetails.addClientId(builder, clientIdOffset);
    AuthDetails.addRealmId(builder, realmIdOffset);
    return AuthDetails.endAuthDetails(builder);
  }

  public static void startAuthDetails(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addRealmId(FlatBufferBuilder builder, int realmIdOffset) { builder.addOffset(0, realmIdOffset, 0); }
  public static void addClientId(FlatBufferBuilder builder, int clientIdOffset) { builder.addOffset(1, clientIdOffset, 0); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(2, userIdOffset, 0); }
  public static void addIpAddress(FlatBufferBuilder builder, int ipAddressOffset) { builder.addOffset(3, ipAddressOffset, 0); }
  public static int endAuthDetails(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

