// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers.events;

public final class OperationType {
  private OperationType() { }
  public static final byte CREATE = 0;
  public static final byte UPDATE = 1;
  public static final byte DELETE = 2;
  public static final byte ACTION = 3;

  public static final String[] names = { "CREATE", "UPDATE", "DELETE", "ACTION", };

  public static String name(int e) { return names[e]; }
}

