// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers.events;

public final class ResourceType {
  private ResourceType() { }
  public static final byte REALM = 0;
  public static final byte REALM_ROLE = 1;
  public static final byte REALM_ROLE_MAPPING = 2;
  public static final byte REALM_SCOPE_MAPPING = 3;
  public static final byte AUTH_FLOW = 4;
  public static final byte AUTH_EXECUTION_FLOW = 5;
  public static final byte AUTH_EXECUTION = 6;
  public static final byte AUTHENTICATOR_CONFIG = 7;
  public static final byte REQUIRED_ACTION = 8;
  public static final byte IDENTITY_PROVIDER = 9;
  public static final byte IDENTITY_PROVIDER_MAPPER = 10;
  public static final byte PROTOCOL_MAPPER = 11;
  public static final byte USER = 12;
  public static final byte USER_LOGIN_FAILURE = 13;
  public static final byte USER_SESSION = 14;
  public static final byte USER_FEDERATION_PROVIDER = 15;
  public static final byte USER_FEDERATION_MAPPER = 16;
  public static final byte GROUP = 17;
  public static final byte GROUP_MEMBERSHIP = 18;
  public static final byte CLIENT = 19;
  public static final byte CLIENT_INITIAL_ACCESS_MODEL = 20;
  public static final byte CLIENT_ROLE = 21;
  public static final byte CLIENT_ROLE_MAPPING = 22;
  public static final byte CLIENT_SCOPE = 23;
  public static final byte CLIENT_SCOPE_MAPPING = 24;
  public static final byte CLUSTER_NODE = 25;
  public static final byte COMPONENT = 26;
  public static final byte AUTHORIZATION_RESOURCE_SERVER = 27;
  public static final byte AUTHORIZATION_RESOURCE = 28;
  public static final byte AUTHORIZATION_SCOPE = 29;
  public static final byte AUTHORIZATION_POLICY = 30;
  public static final byte UNKNOWN = 31;

  public static final String[] names = { "REALM", "REALM_ROLE", "REALM_ROLE_MAPPING", "REALM_SCOPE_MAPPING", "AUTH_FLOW", "AUTH_EXECUTION_FLOW", "AUTH_EXECUTION", "AUTHENTICATOR_CONFIG", "REQUIRED_ACTION", "IDENTITY_PROVIDER", "IDENTITY_PROVIDER_MAPPER", "PROTOCOL_MAPPER", "USER", "USER_LOGIN_FAILURE", "USER_SESSION", "USER_FEDERATION_PROVIDER", "USER_FEDERATION_MAPPER", "GROUP", "GROUP_MEMBERSHIP", "CLIENT", "CLIENT_INITIAL_ACCESS_MODEL", "CLIENT_ROLE", "CLIENT_ROLE_MAPPING", "CLIENT_SCOPE", "CLIENT_SCOPE_MAPPING", "CLUSTER_NODE", "COMPONENT", "AUTHORIZATION_RESOURCE_SERVER", "AUTHORIZATION_RESOURCE", "AUTHORIZATION_SCOPE", "AUTHORIZATION_POLICY", "UNKNOWN", };

  public static String name(int e) { return names[e]; }
}

