// automatically generated by the FlatBuffers compiler, do not modify

package flatbuffers.events;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AdminEvent extends Table {
  public static AdminEvent getRootAsAdminEvent(ByteBuffer _bb) { return getRootAsAdminEvent(_bb, new AdminEvent()); }
  public static AdminEvent getRootAsAdminEvent(ByteBuffer _bb, AdminEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AdminEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long time() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String realmId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer realmIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public AuthDetails authDetails() { return authDetails(new AuthDetails()); }
  public AuthDetails authDetails(AuthDetails obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public byte resourceType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte operationType() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String resourcePath() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer resourcePathAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public String representation() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer representationAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public String error() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }

  public static int createAdminEvent(FlatBufferBuilder builder,
      long time,
      int realmIdOffset,
      int authDetailsOffset,
      byte resourceType,
      byte operationType,
      int resourcePathOffset,
      int representationOffset,
      int errorOffset) {
    builder.startObject(8);
    AdminEvent.addTime(builder, time);
    AdminEvent.addError(builder, errorOffset);
    AdminEvent.addRepresentation(builder, representationOffset);
    AdminEvent.addResourcePath(builder, resourcePathOffset);
    AdminEvent.addAuthDetails(builder, authDetailsOffset);
    AdminEvent.addRealmId(builder, realmIdOffset);
    AdminEvent.addOperationType(builder, operationType);
    AdminEvent.addResourceType(builder, resourceType);
    return AdminEvent.endAdminEvent(builder);
  }

  public static void startAdminEvent(FlatBufferBuilder builder) { builder.startObject(8); }
  public static void addTime(FlatBufferBuilder builder, long time) { builder.addLong(0, time, 0L); }
  public static void addRealmId(FlatBufferBuilder builder, int realmIdOffset) { builder.addOffset(1, realmIdOffset, 0); }
  public static void addAuthDetails(FlatBufferBuilder builder, int authDetailsOffset) { builder.addOffset(2, authDetailsOffset, 0); }
  public static void addResourceType(FlatBufferBuilder builder, byte resourceType) { builder.addByte(3, resourceType, 0); }
  public static void addOperationType(FlatBufferBuilder builder, byte operationType) { builder.addByte(4, operationType, 0); }
  public static void addResourcePath(FlatBufferBuilder builder, int resourcePathOffset) { builder.addOffset(5, resourcePathOffset, 0); }
  public static void addRepresentation(FlatBufferBuilder builder, int representationOffset) { builder.addOffset(6, representationOffset, 0); }
  public static void addError(FlatBufferBuilder builder, int errorOffset) { builder.addOffset(7, errorOffset, 0); }
  public static int endAdminEvent(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishAdminEventBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

